spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/admin
spring.datasource.username=admin
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
sensor.values.poll-interval=60000
sensor.values.url=http://192.168.0.64/sensorvalues
socketio.host=0.0.0.0
socketio.port=9092
socketio.allowed-origin=*
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

